changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Device support
      labels: [device, hardware]
    - title: Fixes
      labels: [bug, fix]
    - title: Packaging and installation
      labels: [packaging, recovery]
    - title: Other changes
      labels: ['*']
